### ISSUE TITLE
希望可以缓存一下缩略图

### ISSUE THREAD

**Issue by ljyloo** [chenh96/project-pistol#1]
因为ex/eh的画廊是不可以更新的(要更新画廊只能删除原来的创建新的)，其实画廊创建的时候就固定死了，缩略图跟内容都是，唯一会变化的只有tags和评论，所以其实可以缓存一下的，这样不用每次打开都重新加载了

**Comment by chenh96** [comment]
可以，应该花不了多少时间。

**Comment by chenh96** [comment]
已经更新了图片缓存功能，使用较为简便的方法来解决的。
不过由于 e 站本身设定上就比较坑，想要实现完全秒加载的效果很麻烦。

**Comment by ljyloo** [comment]
看了一下commit，代码量挺大的，辛苦了。但是缓存有点粗暴，例如我看完一本，它是缓存了，但是再点击下载又要重新下载。然后一个画廊的主页其实会变化的只有评分、标签和评论，图片链接都是固定的，不需要重新解析一次了。但是缓存有总比没好太多，感谢。

**Comment by chenh96** [comment]
下载的话是直接移动缓存好的图片。
仅仅缓存图片只需要加很少的代码，但如果要避免解析的话改动会比较大。
因为前期对 e 站的解析没什么经验，导致整体设计比较糟糕。
所以我将会收集一些比较令人头痛的问题，然后更新一个大版本来解决。

**Comment by ljyloo** [comment]
我觉得你写的UI很好，但是我想自己写一个backend，不知道你这个frontend跟backend的耦合程度高不高

**Comment by chenh96** [comment]
由于为了快速实现简单粗暴的效果，前后端是相互适配的，耦合性不低。
而且一般都是前端配合后端进行修改，所以替换后端的话会比较难（不建议）。
接口相关的功能在以下两个包中，可以先参考一下：
cloud.chenh.bolt.data.web（提供接口）
cloud.chenh.bolt.schedule（定时向 WebSocket 发送下载内容）
前端我为了省事，把接口获取相关的逻辑直接写到了 .vue 页面内。
