### ISSUE TITLE
希望添加韩漫的图片分割

### ISSUE THREAD

**Issue by zx900930** [chenh96/project-pistol#2]
添加一个图片大小符合屏幕宽度的选项
例子:
https://exhentai.org/g/1610270/d0caa5bb24/

或者做个简单的条件判断：图片 height/width >  2*(设备height/width) 时自动切割并保存为2张图片再显示出来

**Comment by chenh96** [comment]
这种还是加个滚动条算了。

**Comment by zx900930** [comment]
很惊讶的是楼主这个vue写的project在iOS 9居然也能正常显示。
之前我写了个在iOS 9的webkit下面就是各种xxx is not a function

**Comment by chenh96** [comment]
这我倒没料到，大概是因为我JS的写法比较原始……

**Comment by chenh96** [comment]
新的版本加入了垂直阅读模式方便阅读这种长图，做法是加一个按钮来切换垂直滚动。
垂直阅读模式下不支持用滑轨来拖动翻页，可以直接用滚动条来代替。

**Comment by zx900930** [comment]
> 新的版本加入了垂直阅读模式方便阅读这种长图，做法是加一个按钮来切换垂直滚动。
> 垂直阅读模式下不支持用滑轨来拖动翻页，可以直接用滚动条来代替。

谢谢，等你push完我试试看

**Comment by zx900930** [comment]
![WeChat Image_20200419172800](https://user-images.githubusercontent.com/734749/79692039-29083b80-8263-11ea-8871-6bba1c8e4ce0.jpg)
切换成垂直模式后图片挤成一团了，console里也没有报错。

**Comment by chenh96** [comment]
有可能是浏览器缓存的原因，我在开发的时候常常被Safari的缓存所困扰。Safari不会因为刷新来更新页面的代码。
可以尝试清理一下Safari的缓存。不行的话我再看看。

**Comment by zx900930** [comment]
清理完缓存还是一样，应该是js执行出错，生成的html多了一个=""：
`<div data-v-37ad8048="" class="slide vertical"** =""**>
<img data-v-37ad8048="" data-src="http://82.64.152.55:8848/api//gallery/image/view?url=https://e-hentai.org/s/0c6b91bcce/1615639-2" src="http://82.64.152.55:8848/api//gallery/image/view?url=https://e-hentai.org/s/0c6b91bcce/1615639-2" lazy="loaded" ="">
</div>
`
本来应该是
`<div data-v-37ad8048="" class="slide vertical"><img data-v-37ad8048="" data-src="http://82.64.152.55:8848/api//gallery/image/view?url=https://exhentai.org/s/0c6b91bcce/1616432-2" src="http://82.64.152.55:8848/api//gallery/image/view?url=https://exhentai.org/s/0c6b91bcce/1616432-2" lazy="loaded"></div>`

**Comment by chenh96** [comment]
总算上传成功了，可能是由于加了 vertical 类之后的 css 中写的 width: auto; 在不同浏览器下的效果不同，试试最新的吧。

**Comment by zx900930** [comment]
非常感谢！ 现在显示正常了！
