### ISSUE TITLE
希望能添加一个预载的功能

### ISSUE THREAD

**Issue by zxhzxhz** [chenh96/project-pistol#3]
首先感谢开发这个app，目前在ipad上体验感觉很良好。
但是梯子并没有达到秒载的级别，所以每翻一页大概需要等待2-5秒才能刷出下一页，
希望能够看到一页的时候提前载入3-5页内容从而使观看更加流畅。

**Comment by chenh96** [comment]
新的版本加入了提前预载下一页的功能，但是要预载3到5页才能满足的话，建议还是更换稍微好一点的梯子😂
